In [9]:
import random
import json
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer


class Review:
    def __init__(self, text, score):
        self.text = text
        self.score = score
        self.sentiment = self.get_sentiment()
        
class sentiment:
    NEGATIVE = "NEGATIVE"
    NEUTRAL = "NEUTRAL"
    POSITIVE = "POSITIVE"
        
    def get_sentiment(self):
        if self.score <= 2:
            return sentiment.NEGATIVE
        if self.score == 3:
            return sentiment.NEUTRAL
        else:
            return sentiment.POSITIVE

In [11]:
file_name = 'C:/Users/User/Downloads/Books_small.json'

reviews = []
with open(file_name) as f:
    for line in f:
        review = json.loads(line)
        reviews.append(Review(review['reviewText'], review['overall']))

reviews[2].text

'Very simple book, but leaves you feeling good.  No over the top sex scenes, no graphic violence.  Just a simple book that talks touches on child abuse and dysfunction in a family.  I liked it because the author did not go into graphic detail about the abuse, but instead focused how it affected the people involved.  Good story, good characters.'

In [15]:
#len(reviews)

training, test = train_test_split(reviews,test_size = 0.33)
#len(test)

330

In [47]:
#print(training[0].text)
train_x = [x.text for x in training]
train_y = [x.sentiment for x in training]


test_x = [x.text for x in test]
test_y = [x.sentiment for x in test]

In [55]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

vectorizer = CountVectorizer()
train_x_vectors = vectorizer.fit_transform(train_x)

test_x_vectors = vectorizer.transform(test_x)

print(train_x[0])
print(train_x_vectors[0].toarray())
print(test_x_vectors[0].toarray())

I tried this book on the strength of the author's previous book, Behind the Green Curtain.  I liked this one as well, and although they are two very different books, I have similar things to say about this one, which is that I enjoy her writing but am not really a fan of her plot twists.  This book has two plot twists; the first one takes place about halfway through and is fine, but the second one takes place in the final pages of the book and I could have done without it.  For a moment, it felt like the rug was pulled out from under me, and although the author put it back, it was rather jolting.  I think things could have accomplished it in a different way.  Having said that, her story flows, the characters are interesting, there is some humor, and  I like her analogies and imagery.
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]


In [76]:
from sklearn import svm

clf_svm = svm.SVC(kernel='linear')

clf_svm.fit(train_x_vectors, train_y)

test_x[0]
test_x_vectors[0]

#clf_svm.predit(test_x_vectors[0])

<1x7375 sparse matrix of type '<class 'numpy.int64'>'
	with 47 stored elements in Compressed Sparse Row format>

In [75]:
from sklearn.tree import DecisionTreeClassifier

clf_dec = DecisionTreeClassifier()

clf_dec.fit(train_x_vectors, train_y)

test_x[0]
clf_dec.predict(test_x_vectors[0])

array(['POSITIVE'], dtype='<U8')

In [77]:
from sklearn.naive_bayes import GaussianNB

clf_gnb = DecisionTreeClassifier()

clf_gnb.fit(train_x_vectors, train_y)

test_x[0]
clf_gnb.predict(test_x_vectors[0])

array(['POSITIVE'], dtype='<U8')

In [78]:
from sklearn.linear_model import LogisticRegression

clf_log = LogisticRegression()

clf_log.fit(train_x_vectors, train_y)

test_x[0]
clf_log.predict(test_x_vectors[0])

c:\users\user\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array(['POSITIVE'], dtype='<U8')

In [81]:
print(clf_dec.score(test_x_vectors, test_y))
print(clf_gnb.score(test_x_vectors, test_y))
print(clf_log.score(test_x_vectors, test_y))

0.7303030303030303
0.7181818181818181
0.8393939393939394


In [86]:
from sklearn.metrics import f1_score
f1_score(test_y,clf_gnb.predict(test_x_vectors), average = None, labels=[sentiment.POSITIVE,sentiment.NEUTRAL,sentiment.NEGATIVE])

array([0.84229391, 0.03278689, 0.04878049])